site :opscode
cookbook 'apache2'
cookbook 'php', github: "kambayashia/cookbooks-php"
cookbook 'emacs'
cookbook 'git'
cookbook 'mysql', github: "kambayashia/cookbooks-mysql", branch: "debian7"
cookbook "apt"
